### ISSUE TITLE
播放器改版后，视频加载不出

### ISSUE THREAD

**Issue by ssxwcz** [sakuyaa/gm_scripts#3]
![image](https://user-images.githubusercontent.com/43665491/88934500-46619280-d2b3-11ea-98d9-5249fa479ac7.png)
启用弹幕姬脚本后，视频播放器无法加载出来，应该和播放器加载产生了冲突 https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666359865

**Comment by sakuyaa** [comment]
刚刚更新了，暂时试着再次延时等播放器加载了

**Comment by sakuyaa** [comment]
最新版已经修复了，原来是b站默默地把加载前显示的“历史累计弹幕数--”改成“历史累计弹幕数undefined”了。。。

**Comment by ssxwcz** [comment]
感谢，可以了
